### ISSUE TITLE
undefined local variable or method `coll' for Stocktrader:Class (NameError)

### ISSUE THREAD

**Issue by marcusl33beach** [marcusl33beach/stock_trader#1]
I am getting the below error when calling the 'COL' method from the mongo driver. I believe I am using older syntax with the newer driver.

C:\Ruby22-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/mrbea/Documents/projects/stock_trader/stock_trader.rb
D, [2016-06-20T22:55:09.440342 #10912] DEBUG -- : MONGODB | Adding mongodb01:27017 to the cluster.
Connected to mongo...
C:/Users/mrbea/Documents/projects/stock_trader/helper.rb:31:in `mongo_add': undefined local variable or method `coll' for Stocktrader:Class (NameError)
	from C:/Users/mrbea/Documents/projects/stock_trader/stock_trader.rb:23:in `block in <top (required)>'
	from C:/Users/mrbea/Documents/projects/stock_trader/stock_trader.rb:21:in `each'
	from C:/Users/mrbea/Documents/projects/stock_trader/stock_trader.rb:21:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1

**Comment by marcusl33beach** [comment]
Undefined local variable.
