### ISSUE TITLE
How to pass JSON into Mongo with Ruby drive?

### ISSUE THREAD

**Issue by marcusl33beach** [marcusl33beach/stock_trader#2]
> ruby stock_trader.rb
D, [2016-06-21T23:03:17.849409 #27316] DEBUG -- : MONGODB | Adding mongodb01:27017 to the cluster.
Connected to mongo...
C:/Users/mrbea/Documents/projects/stock_trader/helper.rb:52:in `mongo_add': uninitialized constant Database::ActiveSupport (NameError)
        from stock_trader.rb:23:in `block in <main>'
        from stock_trader.rb:21:in `each'
        from stock_trader.rb:21:in `<main>'

**Comment by marcusl33beach** [comment]
Garbage in Garbage out
